# Generated by Django 3.2 on 2021-04-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='city',
            new_name='city_state_country',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='city',
            new_name='city_state_country',
        ),
        migrations.RenameField(
            model_name='organizationposts',
            old_name='city',
            new_name='city_state_country',
        ),
        migrations.RemoveField(
            model_name='member',
            name='country',
        ),
        migrations.RemoveField(
            model_name='member',
            name='state',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='state',
        ),
        migrations.RemoveField(
            model_name='organizationposts',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organizationposts',
            name='state',
        ),
    ]
