# Generated by Django 3.2 on 2021-04-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20210419_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Address_line',
            new_name='addressLocation',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='city_state_country',
            new_name='addressStreet',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='Address_line',
            new_name='addressLocation',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='city_state_country',
            new_name='addressStreet',
        ),
        migrations.RenameField(
            model_name='organizationposts',
            old_name='Address_line',
            new_name='addressLocation',
        ),
        migrations.RenameField(
            model_name='organizationposts',
            old_name='city_state_country',
            new_name='addressStreet',
        ),
    ]
