# Generated by Django 3.2 on 2021-04-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_auto_20210421_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationposts',
            name='addressLocation',
            field=models.CharField(max_length=100),
        ),
    ]
