# Generated by Django 3.2 on 2021-04-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_alter_organizationposts_addresslocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['createdAt']},
        ),
    ]
