# Generated by Django 3.2 on 2021-04-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationposts',
            options={'ordering': ['createdAt']},
        ),
    ]
