# Generated by Django 3.2 on 2021-04-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_alter_organizationposts_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='addressStreet',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='addressStreet',
        ),
        migrations.RemoveField(
            model_name='organizationposts',
            name='addressStreet',
        ),
    ]
