# Generated by Django 3.2 on 2021-04-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_auto_20210423_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationposts',
            name='postedByOrganizationEmail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
