# Generated by Django 3.2 on 2021-04-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_organizationposts_postedbyorganizationemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='addressLocation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='addressLocation',
            field=models.CharField(max_length=100),
        ),
    ]
