# Generated by Django 3.2 on 2021-04-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_auto_20210423_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='addressLocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='addressLocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
