# Generated by Django 3.2 on 2021-04-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0012_auto_20210423_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='addressLocation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='addressLocation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
