# Generated by Django 3.2.8 on 2021-12-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0015_videoposts_postedbyorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoposts',
            name='postedByOrganizationEmail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
