# Generated by Django 4.1.3 on 2022-11-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0016_videoposts_postedbyorganizationemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
